{
"adareda":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/adaleyi.webp",
"adaleyi":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/adaleyi.webp",
"adareyi":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/adaleyi.webp",
"ආදරේ":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/adaleyi.webp",
"ආදලෙ":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/adaleyi.webp",
"adared":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/adarei%20godak.webp",
 "nehene":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/adarei%20godak.webp",
 "adale ne":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/adarei%20godak.webp",
 "adare ne":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/adarei%20godak.webp",
 "ආදරේ නැ":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/adarei%20godak.webp",
 "ආදලෙ නෑ":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/adarei%20godak.webp",
"bassa":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/bassa.webp",
 "bassi":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/bassa.webp",
 "bakamuni":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/bassa.webp",
 "බස්සා":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/bassa.webp",
 "බස්සි":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/bassa.webp",
 "බකමුනා":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/bassa.webp",
 "බකමූනි":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/bassa.webp",
"gm":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/gm.webp",
 "good morning":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/gm.webp",
 "good monin":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/gm.webp",
 "ගුඩ් මෝනින්":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/gm.webp",
 "උදෑසනක්":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/gm.webp",
"guti":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/guti.webp",
 "gahanawa":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/guti.webp",
 "gahana":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/guti.webp",
 "ගහනවා":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/guti.webp",
 "ගහයි":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/guti.webp",
"hi":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/hi.webp",
 "hey":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/hi.webp",
 "hello":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/hi.webp",
 "හායි":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/hi.webp",
 "හලෝ":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/hi.webp",
"huththa":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/huththa.webp",
 "hutta":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/huththa.webp",
 "hukanawa":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/huththa.webp",
 "hukanna":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/huththa.webp",
 "හුත්":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/huththa.webp",
 "හුකන":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/huththa.webp",
"inno":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/innawada.webp",
 "innawada":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/innawada.webp",
 "idahan":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/innawada.webp",
 "ඉන්නවද":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/innawada.webp",
 "ඉන්න":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/innawada.webp",
"kethmi":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/kethmi.webp",
 "rithu":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/kethmi.webp",
  "කෙත්මි":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/kethmi.webp",
 "රිතු":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/kethmi.webp",
"kukku":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/kukku.webp",
 "kiri":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/kukku.webp",
  "කුක්කු":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/kukku.webp",
 "තන්":"https://github.com/vimanew/ZAIRO-MD-DATABASE/raw/main/autosticker/kukku.webp"
}
